double totalPrize = 0;
String nameS = "",
    mobileS = "",
    mailS = "aswin@mail.com",
    passwordS = "",
    imageS = "assets/images/downloadfile-7.jpg",
    address = "";
double totPrize = 0;
bool checked = false;
